### ISSUE TITLE
Weird behaviour 

### ISSUE THREAD

**Issue by MikhailMS** [hexahedria/biaxial-rnn-music-composition#24]
I tried to run the app with various amount of different midi samples, however after files are loaded I am getting this warning
`/model.py:372: UserWarning: Updating an 'OrderedUpdates' with a non-ordered dictionary with 2+ elements could make your code non-deterministic
  self.walk_input: next_input
/model.py:375: UserWarning: Updating an 'OrderedUpdates' with a non-ordered dictionary with 2+ elements could make your code non-deterministic
  updates.update({hidden:newstate for hidden, newstate, layer in zip(self.walk_hiddens, new_states, self.time_model.layers) if has_hidden(layer)})`

and after that it fails with Memory error
`Traceback (most recent call last):
  File "main.py", line 46, in <module>
    multi_training.trainPiece(m, pcs, 10000)
  File "/LSTM-generator/multi_training.py", line 53, in trainPiece
    error = model.update_fun(*getPieceBatch(pieces))
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 951, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 940, in <lambda>
    self, node)
  File "theano/scan_module/scan_perform.pyx", line 524, in theano.scan_module.scan_perform.perform (/home/.theano/compiledir_Linux-2.6-el6.x86_64-x86_64-with-redhat-6.8-Carbon-x86_64-2.7.13-64/scan_perform/mod.cpp:5862)
  File "/home/.conda/envs/music-generation/lib/python2.7/site-packages/theano/tensor/type.py", line 634, in value_zeros
    return numpy.zeros(shape, dtype=self.dtype)
MemoryError`

I tried to decrease the batch_width and run on both cpu and gpu clusters (there was no warning about memory over-usage from clusters though) so I am kinda lost. What could be an issue?

**Comment by MikhailMS** [comment]
Issue's been discovered. It was my mistake :)

**Comment by XXXXX11123333** [comment]
Can you say - What was the mistake?

**Comment by MikhailMS** [comment]
@MusicxChris it was some time ago, so I cannot remember exactly, but seems like  I had purely composed midi files which caused that error. But it could be due something else, but deletion of those midi files helped me.
